export interface University {
  name: string;
  country: string;
}

export const universities: University[] = [
  { name: "Aberystwyth University", country: "Wales" },
  { name: "Anglia Ruskin University", country: "England" },
  { name: "Balliol College University of Oxford", country: "England" },
  { name: "Bangor University", country: "Wales" },
  { name: "Bath Spa University", country: "England" },
  { name: "Birmingham City University", country: "England" },
  { name: "Bishop Grosseteste University", country: "England" },
  { name: "Blackfriars Hall University of Oxford", country: "England" },
  { name: "Bournemouth University", country: "England" },
  { name: "Brasenose College University of Oxford", country: "England" },
  { name: "Brunel University", country: "England" },
  { name: "Buckinghamshire New University", country: "England" },
  { name: "Canterbury Christ Church University", country: "England" },
  { name: "Cardiff Metropolitan University", country: "Wales" },
  { name: "Cardiff University", country: "Wales" },
  { name: "Christ Church University of Oxford", country: "England" },
  { name: "Coleg Meirion-Dwyfor (FE College)", country: "Wales" },
  { name: "Corpus Christi College University of Oxford", country: "England" },
  { name: "Coventry University", country: "England" },
  { name: "Cranfield University", country: "England" },
  { name: "De Montfort University", country: "England" },
  { name: "Edge Hill University", country: "England" },
  { name: "Exeter College University of Oxford", country: "England" },
  { name: "Falmouth Exeter Plus", country: "England" },
  { name: "Glyndwr University Wrexham", country: "Wales" },
  { name: "Goldsmiths University of London", country: "England" },
  { name: "Graduate Accommodation Office University of Oxford", country: "England" },
  { name: "Green Templeton College University of Oxford", country: "England" },
  { name: "Guildhall School of Music and Drama", country: "England" },
  { name: "Harper Adams University", country: "England" },
  { name: "Harris Manchester College University of Oxford", country: "England" },
  { name: "Hartpury University", country: "England" },
  { name: "Hertford College University of Oxford", country: "England" },
  { name: "Imperial College London", country: "England" },
  { name: "Jesus College University of Oxford", country: "England" },
  { name: "Keble College University of Oxford", country: "England" },
  { name: "Keele University", country: "England" },
  { name: "Kellogg College University of Oxford", country: "England" },
  { name: "King's College London", country: "England" },
  { name: "Kingston University", country: "England" },
  { name: "Lady Margaret Hall University of Oxford", country: "England" },
  { name: "Lancaster University", country: "England" },
  { name: "Leeds Trinity University", country: "England" },
  { name: "Linacre College University of Oxford", country: "England" },
  { name: "Lincoln College University of Oxford", country: "England" },
  { name: "Liverpool Hope University", country: "England" },
  { name: "London School of Economics (University of London)", country: "England" },
  { name: "London South Bank University", country: "England" },
  { name: "Loughborough University", country: "England" },
  { name: "Magdalen College University of Oxford", country: "England" },
  { name: "Manchester Metropolitan University", country: "England" },
  { name: "Mansfield College University of Oxford", country: "England" },
  { name: "Merton College University of Oxford", country: "England" },
  { name: "Middlesex University", country: "England" },
  { name: "New College University of Oxford", country: "England" },
  { name: "Newcastle University", country: "England" },
  { name: "Newman University", country: "England" },
  { name: "Norwich University of the Arts", country: "England" },
  { name: "Nuffield College University of Oxford", country: "England" },
  { name: "Oriel College University of Oxford", country: "England" },
  { name: "Oxford Brookes University", country: "England" },
  { name: "Pembroke College University of Oxford", country: "England" },
  { name: "Queen Mary (University of London)", country: "England" },
  { name: "Queen's University Belfast", country: "Northern Ireland" },
  { name: "Regents Park College University of Oxford", country: "England" },
  { name: "Reuben College University of Oxford", country: "England" },
  { name: "Roehampton University", country: "England" },
  { name: "Royal Agricultural University", country: "England" },
  { name: "Royal Holloway University of London", country: "England" },
  { name: "Sheffield Hallam University", country: "England" },
  { name: "Solent University", country: "England" },
  { name: "Somerville College University of Oxford", country: "England" },
  { name: "St Anne's College University of Oxford", country: "England" },
  { name: "St Antony's College University of Oxford", country: "England" },
  { name: "St Catherine's College University of Oxford", country: "England" },
  { name: "St Chad's College University of Durham", country: "England" },
  { name: "St Cross College University of Oxford", country: "England" },
  { name: "St Edmund Hall University of Oxford", country: "England" },
  { name: "St George's University of London", country: "England" },
  { name: "St Hilda's College University of Oxford", country: "England" },
  { name: "St Hugh's College University of Oxford", country: "England" },
  { name: "St John's College Durham (Independent)", country: "England" },
  { name: "St John's College University of Oxford", country: "England" },
  { name: "St Mary's University Twickenham", country: "England" },
  { name: "St Peter's College University of Oxford", country: "England" },
  { name: "St Stephen's House University of Oxford", country: "England" },
  { name: "Staffordshire University", country: "England" },
  { name: "Swansea University", country: "Wales" },
  { name: "Teesside University", country: "England" },
  { name: "The Queen's College University of Oxford", country: "England" },
  { name: "Trinity College University of Oxford", country: "England" },
  { name: "Ulster University", country: "Northern Ireland" },
  { name: "University College Birmingham", country: "England" },
  { name: "University College London", country: "England" },
  { name: "University College Plymouth St Mark and St John", country: "England" },
  { name: "University College University of Oxford", country: "England" },
  { name: "University for the Creative Arts", country: "England" },
  { name: "University of Bath", country: "England" },
  { name: "University of Birmingham", country: "England" },
  { name: "University of Brighton", country: "England" },
  { name: "University of Bristol", country: "England" },
  { name: "University of Buckingham", country: "England" },
  { name: "University of Central Lancashire", country: "England" },
  { name: "University of Chester", country: "England" },
  { name: "University of Cumbria", country: "England" },
  { name: "University of Derby", country: "England" },
  { name: "University of Durham", country: "England" },
  { name: "University of East Anglia", country: "England" },
  { name: "University of East London", country: "England" },
  { name: "University of Essex", country: "England" },
  { name: "University of Exeter", country: "England" },
  { name: "University of Gloucester", country: "England" },
  { name: "University of Hull", country: "England" },
  { name: "University of Kent", country: "England" },
  { name: "University of Leicester", country: "England" },
  { name: "University Of Lincoln", country: "England" },
  { name: "University of Liverpool", country: "England" },
  { name: "University of London", country: "England" },
  { name: "University of Manchester", country: "England" },
  { name: "University of Northampton", country: "England" },
  { name: "University of Nottingham", country: "England" },
  { name: "University of Plymouth", country: "England" },
  { name: "University of Portsmouth", country: "England" },
  { name: "University of Reading", country: "England" },
  { name: "University of Sheffield", country: "England" },
  { name: "University of South Wales", country: "Wales" },
  { name: "University of Southampton", country: "England" },
  { name: "University of Sunderland", country: "England" },
  { name: "University of Surrey", country: "England" },
  { name: "University of Sussex", country: "England" },
  { name: "University of the West of England Bristol", country: "England" },
  { name: "University of Wales Trinity Saint David", country: "Wales" },
  { name: "University of Warwick", country: "England" },
  { name: "University of Westminster", country: "England" },
  { name: "University of Winchester", country: "England" },
  { name: "University of Wolverhampton", country: "England" },
  { name: "University of Worcester", country: "England" },
  { name: "University of York", country: "England" },
  { name: "Wadham College University of Oxford", country: "England" },
  { name: "Wolfson College University of Oxford", country: "England" },
  { name: "Worcester College University of Oxford", country: "England" },
  { name: "Writtle College", country: "England" },
  { name: "Wycliffe Hall University of Oxford", country: "England" },
  { name: "York St John University", country: "England" },
];
